server:
  port: 8081 #8181
book:
  bookname: Java Code
  price: 45
  random: ${random.int}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: club-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka  #注册 中心已经开启认证
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}